/**
* Generated by PluginGenerator from webgme on Tue Jun 10 2014 17:42:32 GMT-0500 (Central Daylight Time).
*/

define([], function () {
    'use strict';
    return {
        'Component': '/1536183540/698902055',
        'ComponentAssembliesFolder': '/1536183540/530776187',
        'ComponentAssembly': '/1536183540/1802052655',
        'ComponentConnection': '/1536183540/880160036',
        'ComponentsFolder': '/1536183540/981958831',
        'ControlPort': '/1536183540/876420956',
        'DiracStructure': '/1536183540/826875168',
        'DiracStructure2ExternalPortConnection': '/1536183540/337415470',
        'DiracStructure2InternalPortConnection': '/1536183540/386518694',
        'DiracStructureConnection': '/1536183540/371990823',
        'ExternalPort': '/1536183540/1506828321',
        'ExternalPort2DiracStructureConnection': '/1536183540/700567378',
        'ExternalPort2InternalPortConnection': '/1536183540/235279032',
        'ExternalPortConnection': '/1536183540/810388703',
        'FCO': '/1',
        'Gyrator': '/1536183540/654448863',
        'InteractionPort': '/1536183540/2106046558',
        'InternalPort': '/1536183540/787120870',
        'InternalPort2DiracStructureConnection': '/1536183540/1039448685',
        'One': '/1536183540/719125838',
        'PHSLanguage': '/1536183540',
        'Project': '/1536183540/552297840',
        'ProjectsFolder': '/1536183540/1529073288',
        'ResistivePort': '/1536183540/1181723130',
        'StoragePort': '/1536183540/1457390394',
        'Transformer': '/1536183540/1165404211',
        'Zero': '/1536183540/1523457733',
    };
});