/**
* Generated by PluginGenerator from webgme on Mon May 05 2014 14:15:38 GMT-0500 (Central Daylight Time).
*/

define(['plugin/PluginConfig',
    'plugin/PluginBase',
    'plugin/CoreAndMeta/CoreAndMeta/meta'], function (PluginConfig, PluginBase, MetaTypes) {
    'use strict';

    /**
    * Initializes a new instance of CoreAndMeta.
    * @class
    * @augments {PluginBase}
    * @classdesc This class represents the plugin CoreAndMeta.
    * @constructor
    */
    var CoreAndMeta = function () {
        // Call base class' constructor.
        PluginBase.call(this);
        this.metaTypes = MetaTypes;
    };

    // Prototypal inheritance from PluginBase.
    CoreAndMeta.prototype = Object.create(PluginBase.prototype);
    CoreAndMeta.prototype.constructor = CoreAndMeta;

    /**
    * Gets the name of the CoreAndMeta.
    * @returns {string} The name of the plugin.
    * @public
    */
    CoreAndMeta.prototype.getName = function () {
        return "Core and META";
    };

    /**
    * Gets the semantic version (semver.org) of the CoreAndMeta.
    * @returns {string} The version of the plugin.
    * @public
    */
    CoreAndMeta.prototype.getVersion = function () {
        return "0.1.0";
    };

    /**
    * Main function for the plugin to execute. This will perform the execution.
    * Notes:
    * - Always log with the provided logger.[error,warning,info,debug].
    * - Do NOT put any user interaction logic UI, etc. inside this method.
    * - callback always has to be called even if error happened.
    *
    * @param {function(string, plugin.PluginResult)} callback - the result callback
    */
    CoreAndMeta.prototype.main = function (callback) {
        var self = this,
            i,
            pos,
            duplicateNode,
            newNode,
            childNode,
            metaTypeNode;
        // The use of metaTypes instead of self.META is only to get code completion.
        self.updateMETA(self.metaTypes);

        if (!self.activeNode) {
            self.logger.error('No activeNode given');
            self.createMessage(self.rootNode, 'No activeNode given.');
            callback('No activeNode given', self.result);
            return;
        }

        // Duplicate the active-node in side the parent of activeNode.
        duplicateNode = self.core.copyNode(self.activeNode, self.core.getParent(self.activeNode));
        // Create a new FCO node inside the duplicate and set the name and position.
        newNode = self.core.createNode({base: self.metaTypes.FCO, parent: duplicateNode});
        self.core.setAttribute(newNode, 'name', 'newNodeInDuplicate');
        self.core.setRegistry(newNode, 'position', {x: 150, y: 150});
        // Create three new child nodes inside the newNode.
        for (i = 0; i < 3; i += 1) {
            childNode = self.core.createNode({base: self.metaTypes.FCO, parent: newNode});
            self.core.setAttribute(childNode, 'name', 'childNode' + i.toString());
            self.core.setRegistry(childNode, 'position', {x: 100, y: 100 + i * 100});
        }
        // Load the children nodes (asynchronously) of newNode and log their names and positions and metaTypes.
        self.core.loadChildren(newNode, function (err, children) {
            if (err) {
                self.createMessage(newNode, 'Could not load children.');
                return callback('Could not load children of newNode', self.result);
            }
            for (i = 0; i < children.length; i += 1) {
                metaTypeNode = self.getMetaType(children[i]);
                pos = self.core.getRegistry(children[i], 'position');
                self.logger.info('Child Node "' + self.core.getAttribute(children[i], 'name') + '"');
                self.logger.info('is of type "' + self.core.getAttribute(metaTypeNode, 'name') + '"');
                self.logger.info('and has position (' + pos.x.toString() + ', ' + pos.y.toString() + ').');
            }

            self.save('added obj', function (err) {
                if (err) {
                    self.createMessage(self.rootNode, 'Could not save changes in project.');
                    return callback('Could not save changes in project.', self.result);
                }
                self.result.setSuccess(true);
                callback(null, self.result);
            });
        });
    };

    return CoreAndMeta;
});