/**
* Generated by MockModelGenerator from webgme on Tue Apr 22 2014 17:28:29 GMT-0500 (Central Daylight Time).
*/

define([], function () {
    'use strict';
    return function (core) {
        var meta = {};

        meta.FCO = core.createNode({});
        core.setAttribute(meta.FCO, 'name', 'FCO');

        meta.ConnectionElement = core.createNode({base: meta.FCO});
        core.setAttribute(meta.ConnectionElement, 'name', 'ConnectionElement');

        meta.Language = core.createNode({base: meta.FCO});
        core.setAttribute(meta.Language, 'name', 'Language');

        meta.ModelElement = core.createNode({base: meta.FCO});
        core.setAttribute(meta.ModelElement, 'name', 'ModelElement');

        meta.ModelRef = core.createNode({base: meta.FCO});
        core.setAttribute(meta.ModelRef, 'name', 'ModelRef');

        meta.PortElement = core.createNode({base: meta.FCO});
        core.setAttribute(meta.PortElement, 'name', 'PortElement');

        return meta;
    };
});