/**
* Generated by MockModelGenerator from webgme on Wed Apr 23 2014 12:25:01 GMT-0500 (Central Daylight Time).
*/

define(['mocks/CoreMock', './META'], function (CoreMock, createMeta) {
    'use strict';
    var core = new CoreMock(1),
        META = createMeta(core),
        options;

    options = {
        base: META.ModelElement,
        parent: core._rootNode,
        attr: {
            'Artie': '9fe770348f6d41aeaa8a8530eb679bd9b7b3bcdf',
            'name': 'Models',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ReferenceExample',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__93c9cb88_ffbc_42fb_4569_7e76b8105152 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__93c9cb88_ffbc_42fb_4569_7e76b8105152,
        attr: {
            'name': 'm',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__dc1684a5_42e2_2a9e_0a84_a3e6e7144846 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__dc1684a5_42e2_2a9e_0a84_a3e6e7144846,
        attr: {
            'name': 'p',
        }
    };
    var ID__f4022fa5_148e_3917_0872_e11d595739bb = core.createNode(options);

    options = {
        base: META.ModelRef,
        parent: ID__93c9cb88_ffbc_42fb_4569_7e76b8105152,
        attr: {
            'name': 'm-ref',
        }
    };
    var ID__37a0b0e0_3462_3873_572e_da2baf9934cd = core.createNode(options);

    options = {
        base: null,
        parent: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ParentExample2',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__819ad5cb_730d_6e89_00fd_a9afd4950ec4 = core.createNode(options);

    options = {
        base: null,
        parent: ID__819ad5cb_730d_6e89_00fd_a9afd4950ec4,
        attr: {
            'name': 'm_parent',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__f55487d1_3382_1a71_ddf0_cadd493dc844 = core.createNode(options);

    options = {
        base: null,
        parent: ID__f55487d1_3382_1a71_ddf0_cadd493dc844,
        attr: {
            'name': 'm_child',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__cc209697_3701_1c89_c3f1_b0cf7719c228 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ConnectionExample',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port1',
        }
    };
    var ID__739ab15e_66d9_58ad_b13a_55b34f3d0902 = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var ID__a3e45f40_04f2_1841_3902_2e85934a6202 = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var ID__fc7eb2df_e5e5_d0a4_ca3d_c649990c88d5 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'm1',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__71e07d33_b513_041b_3db8_6bdd3af291c5 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__71e07d33_b513_041b_3db8_6bdd3af291c5,
        attr: {
            'name': 'p1',
        }
    };
    var ID__7866081a_696c_e82e_d8d2_a64ee2025f20 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port2',
        }
    };
    var ID__3bcf35ad_623a_5cf1_29b4_d31e5bfe881b = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port3',
        }
    };
    var ID__4a442956_984b_8cf1_68c7_0bb3310a5e0d = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var ID__593c9f6b_2d6c_565f_1fa9_f61e9c310a30 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ParentExample',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__90d4ea37_2838_0686_adfd_19ae2d7195fa = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__90d4ea37_2838_0686_adfd_19ae2d7195fa,
        attr: {
            'name': 'm_parent',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__e8ed0ee5_68b7_727e_70f0_7adcb0d9537a = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__e8ed0ee5_68b7_727e_70f0_7adcb0d9537a,
        attr: {
            'name': 'm_child',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__d1991fa3_6c34_7486_6ef1_00ce8efd5916 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'RecursiveChildrenExample',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__03f45eef_42a9_3b81_6577_83ae433824ef = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__03f45eef_42a9_3b81_6577_83ae433824ef,
        attr: {
            'name': 'm2',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__a4168876_9c76_28c2_6b22_113f1fbebdcd = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__a4168876_9c76_28c2_6b22_113f1fbebdcd,
        attr: {
            'name': 'm21',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__7dcad426_0f78_5f9f_588f_51d803896cbb = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__7dcad426_0f78_5f9f_588f_51d803896cbb,
        attr: {
            'name': 'p212',
        }
    };
    var ID__dd0c24c2_f924_6ce3_7c7a_1e96538b3d32 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__03f45eef_42a9_3b81_6577_83ae433824ef,
        attr: {
            'name': 'm1',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__4976900a_6e45_134e_114d_ee8f12015be5 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'm11',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__e00588b0_d926_f782_12cd_3fb0f6eea3ef = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__e00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'p111',
        }
    };
    var ID__92579513_ea00_d390_5ace_c50bcf7c38ec = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__e00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'm111',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__34c7391c_7653_ea5f_47fc_6bd502c75c78 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__34c7391c_7653_ea5f_47fc_6bd502c75c78,
        attr: {
            'name': 'p1111',
        }
    };
    var ID__97aed669_8713_aefb_0fc4_860eb1b31f33 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID__e00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'm112',
            'Artie': '',
            'Prio': 1,
            'Ratio': 1.1,
            'IsActive': true,
            'Desc': 'This is a Model',
            'Choice': 'Second',
        }
    };
    var ID__cb868977_4fd6_c06a_646c_36924752d349 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'p12',
        }
    };
    var ID__3f0eef4f_a783_105c_e591_3780c782b5bb = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID__4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'p11',
        }
    };
    var ID__b7d9e39f_8b81_e258_523d_53396e87695b = core.createNode(options);


// ---------------------- Bases for nodes with non-meta bases -------------------------
    ID__819ad5cb_730d_6e89_00fd_a9afd4950ec4.pointers.base = core.getPath(ID__90d4ea37_2838_0686_adfd_19ae2d7195fa);
    ID__f55487d1_3382_1a71_ddf0_cadd493dc844.pointers.base = core.getPath(ID__e8ed0ee5_68b7_727e_70f0_7adcb0d9537a);
    ID__cc209697_3701_1c89_c3f1_b0cf7719c228.pointers.base = core.getPath(ID__d1991fa3_6c34_7486_6ef1_00ce8efd5916);

// ---------------------- Pointers (e.g. connections) ---------------------------------
    core.setPointer(ID__37a0b0e0_3462_3873_572e_da2baf9934cd, 'ref', ID__dc1684a5_42e2_2a9e_0a84_a3e6e7144846);
    core.setPointer(ID__a3e45f40_04f2_1841_3902_2e85934a6202, 'src', ID__4a442956_984b_8cf1_68c7_0bb3310a5e0d);
    core.setPointer(ID__a3e45f40_04f2_1841_3902_2e85934a6202, 'dst', ID__4a442956_984b_8cf1_68c7_0bb3310a5e0d);
    core.setPointer(ID__fc7eb2df_e5e5_d0a4_ca3d_c649990c88d5, 'src', ID__739ab15e_66d9_58ad_b13a_55b34f3d0902);
    core.setPointer(ID__fc7eb2df_e5e5_d0a4_ca3d_c649990c88d5, 'dst', ID__7866081a_696c_e82e_d8d2_a64ee2025f20);
    core.setPointer(ID__593c9f6b_2d6c_565f_1fa9_f61e9c310a30, 'src', ID__3bcf35ad_623a_5cf1_29b4_d31e5bfe881b);
    core.setPointer(ID__593c9f6b_2d6c_565f_1fa9_f61e9c310a30, 'dst', ID__739ab15e_66d9_58ad_b13a_55b34f3d0902);

    return {
        core: core,
        META: META,
        activeNode: ID__957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        connectionExample: ID__eb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        parentExample: ID__90d4ea37_2838_0686_adfd_19ae2d7195fa,
        mParent: ID__e8ed0ee5_68b7_727e_70f0_7adcb0d9537a,
        referenceExample: ID__93c9cb88_ffbc_42fb_4569_7e76b8105152,
        orgNode: ID__dc1684a5_42e2_2a9e_0a84_a3e6e7144846,
        refNode: ID__37a0b0e0_3462_3873_572e_da2baf9934cd,
        m1: ID__71e07d33_b513_041b_3db8_6bdd3af291c5,
        conn1: ID__37a0b0e0_3462_3873_572e_da2baf9934cd,
        conn2: ID__fc7eb2df_e5e5_d0a4_ca3d_c649990c88d5,
        conn3: ID__593c9f6b_2d6c_565f_1fa9_f61e9c310a30,
        port1: ID__739ab15e_66d9_58ad_b13a_55b34f3d0902,
        port2: ID__3bcf35ad_623a_5cf1_29b4_d31e5bfe881b,
        port3: ID__4a442956_984b_8cf1_68c7_0bb3310a5e0d
    };
});