/**
* Generated by MockModelGenerator from webgme on Tue Apr 22 2014 17:28:29 GMT-0500 (Central Daylight Time).
*/

define(['mocks/CoreMock', './META'], function (CoreMock, createMeta) {
    'use strict';
    var core = new CoreMock(1),
        META = createMeta(core),
        options;

    options = {
        base: META.ModelElement,
        parent: core._rootNode,
        attr: {
            'name': 'Models',
        }
    };
    var ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ReferenceExample',
        }
    };
    var ID93c9cb88_ffbc_42fb_4569_7e76b8105152 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ConnectionExample',
        }
    };
    var IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'ParentExample',
        }
    };
    var ID90d4ea37_2838_0686_adfd_19ae2d7195fa = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4,
        attr: {
            'name': 'RecursiveChildrenExample',
        }
    };
    var ID03f45eef_42a9_3b81_6577_83ae433824ef = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID93c9cb88_ffbc_42fb_4569_7e76b8105152,
        attr: {
            'name': 'm',
        }
    };
    var IDdc1684a5_42e2_2a9e_0a84_a3e6e7144846 = core.createNode(options);

    options = {
        base: META.ModelRef,
        parent: ID93c9cb88_ffbc_42fb_4569_7e76b8105152,
        attr: {
            'name': 'm-ref',
        }
    };
    var ID37a0b0e0_3462_3873_572e_da2baf9934cd = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port1',
        }
    };
    var ID739ab15e_66d9_58ad_b13a_55b34f3d0902 = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var ID930d8f9d_1e7d_6068_67e8_d1c9592126ff = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var IDa3e45f40_04f2_1841_3902_2e85934a6202 = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var IDfc7eb2df_e5e5_d0a4_ca3d_c649990c88d5 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'm1',
        }
    };
    var ID71e07d33_b513_041b_3db8_6bdd3af291c5 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port2',
        }
    };
    var ID3bcf35ad_623a_5cf1_29b4_d31e5bfe881b = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'Port3',
        }
    };
    var ID4a442956_984b_8cf1_68c7_0bb3310a5e0d = core.createNode(options);

    options = {
        base: META.ConnectionElement,
        parent: IDeb3d1ee2_a339_b035_a497_6f58c63cdfc7,
        attr: {
            'name': 'ConnectionElement',
        }
    };
    var ID593c9f6b_2d6c_565f_1fa9_f61e9c310a30 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID03f45eef_42a9_3b81_6577_83ae433824ef,
        attr: {
            'name': 'm2',
        }
    };
    var IDa4168876_9c76_28c2_6b22_113f1fbebdcd = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID03f45eef_42a9_3b81_6577_83ae433824ef,
        attr: {
            'name': 'm1',
        }
    };
    var ID4976900a_6e45_134e_114d_ee8f12015be5 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: IDdc1684a5_42e2_2a9e_0a84_a3e6e7144846,
        attr: {
            'name': 'p',
        }
    };
    var IDf4022fa5_148e_3917_0872_e11d595739bb = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID90d4ea37_2838_0686_adfd_19ae2d7195fa,
        attr: {
            'name': 'm_parent',
        }
    };
    var IDe8ed0ee5_68b7_727e_70f0_7adcb0d9537a = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: IDa4168876_9c76_28c2_6b22_113f1fbebdcd,
        attr: {
            'name': 'm21',
        }
    };
    var ID7dcad426_0f78_5f9f_588f_51d803896cbb = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID71e07d33_b513_041b_3db8_6bdd3af291c5,
        attr: {
            'name': 'p1',
        }
    };
    var ID7866081a_696c_e82e_d8d2_a64ee2025f20 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: ID4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'm11',
        }
    };
    var IDe00588b0_d926_f782_12cd_3fb0f6eea3ef = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'p12',
        }
    };
    var ID3f0eef4f_a783_105c_e591_3780c782b5bb = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID4976900a_6e45_134e_114d_ee8f12015be5,
        attr: {
            'name': 'p11',
        }
    };
    var IDb7d9e39f_8b81_e258_523d_53396e87695b = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: IDe8ed0ee5_68b7_727e_70f0_7adcb0d9537a,
        attr: {
            'name': 'm_child',
        }
    };
    var IDd1991fa3_6c34_7486_6ef1_00ce8efd5916 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID7dcad426_0f78_5f9f_588f_51d803896cbb,
        attr: {
            'name': 'p212',
        }
    };
    var IDdd0c24c2_f924_6ce3_7c7a_1e96538b3d32 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: IDe00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'p111',
        }
    };
    var ID92579513_ea00_d390_5ace_c50bcf7c38ec = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: IDe00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'm111',
        }
    };
    var ID34c7391c_7653_ea5f_47fc_6bd502c75c78 = core.createNode(options);

    options = {
        base: META.ModelElement,
        parent: IDe00588b0_d926_f782_12cd_3fb0f6eea3ef,
        attr: {
            'name': 'm112',
        }
    };
    var IDcb868977_4fd6_c06a_646c_36924752d349 = core.createNode(options);

    options = {
        base: META.PortElement,
        parent: ID34c7391c_7653_ea5f_47fc_6bd502c75c78,
        attr: {
            'name': 'p1111',
        }
    };
    var ID97aed669_8713_aefb_0fc4_860eb1b31f33 = core.createNode(options);


    return {
        core: core,
        META: META,
        activeNode: ID957a9d0e_8dfb_94e5_155b_7dff7c931bd4
    };
});